// <auto-generated />
namespace RambleTracker.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TrackDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TrackDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201508010826343_TrackDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
