// <auto-generated />
namespace RambleTracker.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20150731Tracks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20150731Tracks));
        
        string IMigrationMetadata.Id
        {
            get { return "201507312113072_20150731-Tracks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
